### ISSUE TITLE
Add new stars to departuremono.com glyph manifest

### ISSUE THREAD

**Issue by kimslawson** [rektdeckard/departure-mono#11]
I noticed that the latest release 1.422 (adding the star glyphs) isn't reflected on the manifest of glyphs at [departuremono.com](https://departuremono.com). Could they please be added? Perhaps to the end of the Graphical group, or make it "Graphical, Dingbats", or maybe add a separate "Dingbats" group if more dingbats are planned.

Mockup:
![image](https://github.com/user-attachments/assets/5616e383-334a-4e1f-ac8d-a1c25dc6b082)

If I'm barking up the wrong issue tree here and there's a separate repo for Tobias Fried's site for the font, let me know. I couldn't find one.

**Comment by minoraxis** [comment]
Good catch, @kimslawson. Will update.
