### ISSUE TITLE
Request to add `package-lock.json` for reproducibility concerns

### ISSUE THREAD

**Issue by drupol** [rektdeckard/departure-mono#3]
Hello,

I'm a Nix contributor, and recently I packaged your excellent font for Nix using the binary artifacts: https://github.com/NixOS/nixpkgs/pull/337891.

Upon discovering that this repository is now available and that the fonts can be built from source, I plan to update the Nix package to use the source build.

However, to ensure that we use the exact same dependencies and achieve reproducible builds, the repository is missing a `package-lock.json` file. This file is essential for reproducing the `node_modules` directory accurately, which is critical for the Nix ecosystem and its focus on deterministic builds.

Would it be possible to add the `package-lock.json` file to the repository?

Thank you for your time and for the great work on this project!

Best regards.

**Comment by drupol** [comment]
Thanks for your answer!

Although using the pre-built artefacts from Github could definitely be a solution, Nix is a "source-first" distribution, so I would definitely prefer to build the fonts from the source if it's still OK for you to commit the `package-lock.json` file.

Let me know if you still plan to do it and I'll update the package.

**Comment by rektdeckard** [comment]
We use `pnpm`, not `npm`, and the `pnpm-lock.yaml` file is already committed in this repo 👍

**Comment by drupol** [comment]
Sadly, using `pnpm` file isn't a valid option for building a NPM package in Nix. Would it be possible to commit the `package-lock.json` ?

**Comment by rektdeckard** [comment]
I don't really want to keep two competing lockfiles in this repo, and I'm not sure I understand how it is relevant here? 

> Upon discovering that this repository is now available and that the fonts can be built from source, I plan to update the Nix package to use the source build.

The font is not built from source, the font is just a static asset I serve on the site. You don't need to build the site to get at the font.

**Comment by drupol** [comment]
Oh boy... the coin dropped just now. Thank you and sorry for the misunderstanding !!!

**Comment by drupol** [comment]
New release published: https://github.com/NixOS/nixpkgs/pull/340838

**Comment by rektdeckard** [comment]
No worries! Happy to include installation instruction in our README if you care to make a PR!

**Comment by drupol** [comment]
I will !
