### ISSUE TITLE
Blues (PS hints)

### ISSUE THREAD

**Issue by Finii** [rektdeckard/departure-mono#5]
Hej,

just checked this font (technically) and I noticed that no glyph (of the glyphs I checked) has hints.
There are not even generic BlueZones defined.

From the `src/` I do not recognize the font designer software used. Wanted to check if the omission is a bug or on purpose.

Please just close if this is wanted ;)

_(I had a look into the font file to see if there are actually bitmaps embedded, but that seems to be not the case. Pixelfonts often/usually have the pixel-bitmaps included and they always bother me ;-) )_

**Comment by rektdeckard** [comment]
Ah, I understand the confusion. While it IS a pixel font, it is implemented as a modern vector, not a bitmap. There is no hinting, as each glyph is fixed to an imaginary 5x11 grid and doesn't  change.

The font was made in Glyphs 3.

**Comment by Finii** [comment]
Thanks!
