### ISSUE TITLE
A version with pixels connected

### ISSUE THREAD

**Issue by uni-0000** [rektdeckard/departure-mono#7]
What do you think of a flat version with connected pixels like [KodeMono](https://kodemono.com) or [Debugger](https://dharmatype.com/debugger)?

**Comment by minoraxis** [comment]
Say more — did you mean a kind of beveled look?

**Comment by uni-0000** [comment]
I think so...

**Comment by minoraxis** [comment]
Ok, from what I understand that sounds like a different font. Breaking out of pixels would go against the spirit of Departure. I was thinking of experimenting with a variable font version at some point (with axes like weight, distortion, etc.), but I'd probably stay within pixel bounds.

I'd go with one of the ones you shared if you want that angular look!

**Comment by uni-0000** [comment]
> Breaking out of pixels would go against the spirit of Departure.

I agree, I think what I really wanted was more pixels in the font to better readability in smaller text sizes...
