### ISSUE TITLE
Stars!

### ISSUE THREAD

**Issue by Dr-KerbalMD** [rektdeckard/departure-mono#8]
I'm using Departure Mono to make a text-based game set in space and would like to have a star or two! Both ★ (U+2605) and ☆ (U+2606) would come in handy.

Thanks!

**Comment by rektdeckard** [comment]
Sir, this is a Wendy's!

**Comment by rektdeckard** [comment]
Added in https://github.com/rektdeckard/departure-mono/releases/tag/v1.422 (also the 4-pointed stars)
